### ISSUE TITLE
Question about the performance?

### ISSUE THREAD

**Issue by GWwangshuo** [rewolfiluac/pl-image-classification#8]
Thanks for your nice code. I found the validation accuracy is lower than 0.9, Why? Moreover, I have tried to change the default configure (accelerator: null --> ddp or ddp2), it raises some errors. Could you please give me some hints? Thanks.

**Comment by rewolfiluac** [comment]
Sorry for the late reply.
I have adjusted the default sample.yaml so that the f1 socre is about 0.9.
Please forgive me if this is a random adjustment :)
